# -*- coding: utf-8 -*-
"""News_Headlines_web_scraper.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NuIBAsD9ERoGAQwE39sqABNzDyd5duzV

**Objective:** Scrape top headlines from a news website.

**Tools :** Python, requests, BeautifulSoup

**Deliverables:** Python script + .txt file of headlines
"""

import requests
from bs4 import BeautifulSoup

def scrape_news_headlines(url):
    try:
        response = requests.get(url)
        response.raise_for_status()
        html_content = response.text

        soup = BeautifulSoup(html_content, 'html.parser')
        headlines = []

        for tag in soup.find_all(['h1', 'h2', 'h3']):
            headline_text = tag.get_text(strip=True)
            if headline_text:
                headlines.append(headline_text)

        if not headlines:
            title_tag = soup.find('title')
            if title_tag:
                headlines.append(title_tag.get_text(strip=True))

        if headlines:
            with open('headlines.txt', 'w', encoding='utf-8') as f:
                for headline in headlines:
                    f.write(headline + '\n')
            print(f"Successfully scraped {len(headlines)} headlines and saved to headlines.txt")
        else:
            print("No headlines found. Please check the website's structure or try a different URL.")

    except requests.exceptions.RequestException as e:
        print(f"Error fetching the URL: {e}")
    except Exception as e:
        print(f"An unexpected error occurred: {e}")

if __name__ == "__main__":
    news_url = "https://www.bbc.com/news"
    scrape_news_headlines(news_url)

def read_headlines_from_file(filename="headlines.txt"):
    try:
        with open(filename, 'r', encoding='utf-8') as f:
            print(f"\n--- Contents of {filename} ---")
            for line in f:
                print(line.strip())
            print(f"--- End of {filename} ---")
    except FileNotFoundError:
        print(f"Error: The file '{filename}' was not found.")
    except Exception as e:
        print(f"An error occurred while reading the file: {e}")

if __name__ == "__main__":
    news_url = "https://www.bbc.com/news"
    scrape_news_headlines(news_url)
    read_headlines_from_file("headlines.txt")